---
title: "Build Auction House Database"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
Sys.time()

# R imports
.libPaths("F:/Documents/WoWAH/renv/library/R-4.0/x86_64-w64-mingw32")
library(httr)
library(jsonlite)
library(tidyverse)
library(glue)
library(googledrive)
library(reticulate)
use_condaenv("F:\\Documents\\WoWAH\\renv\\python\\condaenvs\\renv-python\\python.exe")

`%!in%` <- Negate(`%in%`)

source("F:/Documents/WoWAH/data/keys.R")

```

```{python}
# Set up python functions
import requests
from datetime import datetime
import pandas as pd

# Create a new access token
def create_access_token(client_id, client_secret, region = "us"):
   data = { 'grant_type': 'client_credentials' }
   response = requests.post('https://%s.battle.net/oauth/token' % region,
                            data = data,
                            auth = (client_id, client_secret))
   return response.json()

# Get Malf and connected realms data
def get_malfurion(search):
   search = search
   response = requests.get(search)
   return response.json()["auctions"]

response = create_access_token(r['client_id'], r['client_secret'])
token = response['access_token']
```

```{r}
# Create access token string
# Set up search query with Malfurion realm ID
id <- 1175
token <- py$token
search <- glue("https://us.api.blizzard.com/data/wow/connected-realm/{id}/auctions?namespace=dynamic-us&locale=en_US&access_token={token}")
```

```{r}
AH_request <- GET(glue("https://us.api.blizzard.com/data/wow/connected-realm/{id}/auctions?namespace=dynamic-us&locale=en_US&access_token={token}"))
AH_content <- fromJSON(content(AH_request, as = "text"))
# Create df of auction data

AH_df <- as_tibble(AH_content$auctions) %>% 
   mutate(item_id = as.character(item$id))
item_ids <- unique(AH_df$item_id)

# Helper function to chunk id vector
createChunks <- function(x, elements.per.chunk){
   # plain R version
   split(x, rep(seq_along(x), each = elements.per.chunk)[seq_along(x)])

}

item_chunks <- createChunks(item_ids, 50)
search_chunks <- map(item_chunks, function(.x) {
   id_char <- paste(.x, collapse = "||")
   glue("https://us.api.blizzard.com/data/wow/search/item?namespace=static-us&locale=en_US&orderby=id&&_pageSize=1000&id={id_char}&_&access_token={token}")
})
# Need this to be a Python list so I remove names (a named list becomes a python dict)
search_chunks <- unname(search_chunks)
```

```{python}
item_names = []

for search_url in r['search_chunks']:
   response = requests.get(search_url).json()
   response_df = pandas.io.json.json_normalize(response, record_path = ['results'])
   item_names.append(response_df)


item_df = pd.concat(item_names, ignore_index = True, axis = 0, sort = True)

```

```{r}
# Get Item classes index an
item_df <- py$item_df %>% 
   select(data.id, data.is_equippable, data.is_stackable, data.level, data.max_count,
          data.media.id, data.name.en_US,
          data.purchase_price, data.required_level, data.sell_price) %>% 
   rename_all(~stringr::str_replace(., "^data.", "")) %>% 
   rename_at(.vars = vars(ends_with(".en_US")),
             ~ sub('[.]en_US$', '', .)) 

# Create database
library(RSQLite)
library(DBI)

con <- dbConnect(RSQLite::SQLite(), "data/WoWAH_database.sqlite")
dbWriteTable(con, "item_name", item_df, overwrite = TRUE)
```




